#pragma once

#include <SFML/Graphics.hpp>
#include <memory>
#include <string>
#include <vector>

/// \brief owns the render textures used by the level's deferred rendering pipeline.
/// textures are created from window and logical view dimensions and rebuilt on resize.
/// the level renderer receives references to these targets for each render pass.
/// \brief how large each group of render targets is, relative to the image the window shows.
///
/// The targets fall into groups because the passes between them are pairwise: level_background
/// resolves into level, normal_tmp into normal, level into deferred, deferred into the window.
/// Only a whole group can change size.
///
/// The image group is what the player actually sees, so shrinking it costs detail on everything
/// that is not on the pixel grid. The other groups hold low frequency data - light accumulation,
/// surface normals, atmosphere distortion - which survives being rendered smaller and stretched
/// back with texture interpolation, and each step down costs a quarter of the fragments.
struct RenderTargetProfile
{
   float image_scale{1.0f};       //!< level, level_background and deferred: the visible picture
   float lighting_scale{1.0f};    //!< light accumulation and the shadow stencils that mask it
   float normal_scale{1.0f};      //!< the normals the lighting maths reads
   float atmosphere_scale{1.0f};  //!< the atmosphere distortion source

   /// \brief every target at the size of the window image.
   static RenderTargetProfile full();

   /// \brief the console profile: lighting, normals and atmosphere at half size, image untouched.
   static RenderTargetProfile reduced();

   /// \brief resolves a profile by name, falling back to full() for anything unknown.
   /// \param name profile identifier, "full" or "reduced".
   /// \return the matching profile.
   static RenderTargetProfile fromName(const std::string& name);
};

struct RenderTargets
{
   /// \brief foreground world pass with gameplay layers and entities.
   std::shared_ptr<sf::RenderTexture> level;

   /// \brief background world pass for background z layers.
   std::shared_ptr<sf::RenderTexture> level_background;

   /// \brief light accumulation pass generated by dynamic lights.
   std::shared_ptr<sf::RenderTexture> lighting;

   /// \brief second light accumulation texture for lights 4-7 (RGBA channels).
   std::shared_ptr<sf::RenderTexture> lighting2;

   /// \brief normal map used by deferred lighting shaders.
   std::shared_ptr<sf::RenderTexture> normal;

   /// \brief temporary normal buffer used before atmosphere distortion.
   std::shared_ptr<sf::RenderTexture> normal_tmp;

   /// \brief composed deferred output before post processing.
   std::shared_ptr<sf::RenderTexture> deferred;

   /// \brief atmosphere distortion pass texture.
   std::shared_ptr<sf::RenderTexture> atmosphere;

#ifdef GLOW_ENABLED
   /// \brief full-size blur/glow pass texture.
   std::shared_ptr<sf::RenderTexture> blur;

   /// \brief downscaled blur texture used by glow upsampling.
   std::shared_ptr<sf::RenderTexture> blur_scaled;
#endif

   /// \brief conversion factor from logical view units to texture-space units.
   float view_to_texture_scale = 1.0f;

   /// \brief sizes each group of targets relative to the window image.
   /// only the image group is measured in view units, and that group is never scaled down, so
   /// view_to_texture_scale stays independent of the profile.
   RenderTargetProfile profile;

   /// \brief allocates all render textures and computes view-to-texture scaling.
   /// \param video_mode_width window width in pixels.
   /// \param video_mode_height window height in pixels.
   /// \param view_width logical view width used for game rendering.
   /// \param view_height logical view height used for game rendering.
   void create(uint32_t video_mode_width, uint32_t video_mode_height, float view_width, float view_height);

   /// \brief clears existing targets and recreates them for a new window size.
   /// \param video_mode_width resized window width in pixels.
   /// \param video_mode_height resized window height in pixels.
   /// \param view_width logical view width used for game rendering.
   /// \param view_height logical view height used for game rendering.
   void recreateOnResize(uint32_t video_mode_width, uint32_t video_mode_height, float view_width, float view_height);

   /// \brief gets the full list of allocated render textures.
   /// \return const reference to internal texture list for iteration.
   const std::vector<std::shared_ptr<sf::RenderTexture>>& getAll() const;

private:
   /// \brief cached texture list used for bulk operations and logging.
   std::vector<std::shared_ptr<sf::RenderTexture>> _all_textures;
};
