#pragma once

#include <SFML/Graphics.hpp>
#include <memory>
#include <vector>

/// \brief owns the render textures used by the level's deferred rendering pipeline.
/// textures are created from window and logical view dimensions and rebuilt on resize.
/// the level renderer receives references to these targets for each render pass.
struct RenderTargets
{
   /// \brief foreground world pass with gameplay layers and entities.
   std::shared_ptr<sf::RenderTexture> level;

   /// \brief background world pass for background z layers.
   std::shared_ptr<sf::RenderTexture> level_background;

   /// \brief light accumulation pass generated by dynamic lights.
   std::shared_ptr<sf::RenderTexture> lighting;

   /// \brief normal map used by deferred lighting shaders.
   std::shared_ptr<sf::RenderTexture> normal;

   /// \brief temporary normal buffer used before atmosphere distortion.
   std::shared_ptr<sf::RenderTexture> normal_tmp;

   /// \brief composed deferred output before post processing.
   std::shared_ptr<sf::RenderTexture> deferred;

   /// \brief atmosphere distortion pass texture.
   std::shared_ptr<sf::RenderTexture> atmosphere;

   /// \brief full-size blur/glow pass texture.
   std::shared_ptr<sf::RenderTexture> blur;

   /// \brief downscaled blur texture used by glow upsampling.
   std::shared_ptr<sf::RenderTexture> blur_scaled;

   /// \brief conversion factor from logical view units to texture-space units.
   float view_to_texture_scale = 1.0f;

   /// \brief allocates all render textures and computes view-to-texture scaling.
   /// \param video_mode_width window width in pixels.
   /// \param video_mode_height window height in pixels.
   /// \param view_width logical view width used for game rendering.
   /// \param view_height logical view height used for game rendering.
   void create(uint32_t video_mode_width, uint32_t video_mode_height, float view_width, float view_height);

   /// \brief clears existing targets and recreates them for a new window size.
   /// \param video_mode_width resized window width in pixels.
   /// \param video_mode_height resized window height in pixels.
   /// \param view_width logical view width used for game rendering.
   /// \param view_height logical view height used for game rendering.
   void recreateOnResize(uint32_t video_mode_width, uint32_t video_mode_height, float view_width, float view_height);

   /// \brief gets the full list of allocated render textures.
   /// \return const reference to internal texture list for iteration.
   const std::vector<std::shared_ptr<sf::RenderTexture>>& getAll() const;

private:
   /// \brief cached texture list used for bulk operations and logging.
   std::vector<std::shared_ptr<sf::RenderTexture>> _all_textures;
};
