#pragma once

#include "box2d/box2d.h"

#include <memory>
#include <vector>

struct LuaNode;
class FixtureNode;

/// \brief routes box2d contact callbacks into gameplay-specific collision handling.
class GameContactListener : public b2ContactListener
{
public:
   enum class EventType
   {
      Invalid,
      DamageContact,
      SmashEnemyContact
   };

   /// \brief base event queued during contact callbacks and executed after physics stepping.
   struct ContactEvent
   {
      EventType _type;

      /// \brief creates an event with a concrete event type.
      /// \param type event category used for filtering and priority handling.
      explicit ContactEvent(EventType type) : _type(type) {}
      /// \brief executes the deferred event action.
      virtual void execute() {};
   };

   /// \brief deferred event that applies enemy contact damage to the player.
   struct DamageContactEvent : public ContactEvent
   {
      LuaNode* _enemy{nullptr};
      int32_t _damage{0};

      /// \brief creates an empty damage event.
      DamageContactEvent() : ContactEvent(EventType::DamageContact) {}
      /// \brief creates a damage event for a specific enemy and damage amount.
      /// \param enemy enemy lua node that caused the contact.
      /// \param damage damage to apply when the event is executed.
      DamageContactEvent(LuaNode* enemy, int32_t damage)
          : ContactEvent(EventType::DamageContact), _enemy(enemy), _damage(damage) {}

      /// \brief applies queued damage when the source enemy is still valid.
      void execute() override;
   };

   /// \brief deferred event that smashes an enemy and bounces the player upward.
   struct SmashEnemyContactEvent : public ContactEvent
   {
      LuaNode* _enemy{nullptr};

      /// \brief creates an empty smash event.
      SmashEnemyContactEvent() : ContactEvent(EventType::SmashEnemyContact) {}

      /// \brief marks the enemy as smashed and applies the upward rebound impulse.
      void execute() override;
   };

   /// \brief returns the number of non-sensor contacts touching the player head sensor.
   /// \return active head sensor contact count.
   int32_t getPlayerHeadContactCount() const;

   /// \brief returns head contacts that are not friendly or walk-through fixtures.
   /// \return active blocking head contact count.
   int32_t getPlayerHeadContactCollidingCount() const;

   /// \brief returns the number of non-sensor contacts touching the player foot sensor.
   /// \return active foot sensor contact count.
   int32_t getPlayerFootContactCount() const;

   /// \brief returns the number of non-sensor contacts touching the left arm sensor.
   /// \return active left arm sensor contact count.
   int32_t getPlayerArmLeftContactCount() const;

   /// \brief returns the number of non-sensor contacts touching the right arm sensor.
   /// \return active right arm sensor contact count.
   int32_t getPlayerArmRightContactCount() const;

   /// \brief returns left arm contacts that are not friendly or walk-through fixtures.
   /// \return active blocking left arm contact count.
   int32_t getPlayerArmLeftContactCollidingCount() const;

   /// \brief returns right arm contacts that are not friendly or walk-through fixtures.
   /// \return active blocking right arm contact count.
   int32_t getPlayerArmRightContactCollidingCount() const;

   /// \brief returns the number of active contacts involving the player main fixture.
   /// \return active player fixture contact count.
   int32_t getPlayerContactCount() const;

   /// \brief returns active contacts where the player touches deadly fixtures.
   /// \return active deadly contact count.
   int32_t getDeadlyContactCount() const;

   /// \brief returns active contacts between the player and moving platforms.
   /// \return active moving platform contact count.
   int32_t getMovingPlatformContactCount() const;

   /// \brief returns active contacts between the player and death-block platforms.
   /// \return active death-block contact count.
   int32_t getDeathBlockContactCount() const;

   /// \brief reports whether the player was detected as crushed by a platform.
   /// \return true when a crushing scenario was detected.
   bool isPlayerSmashed() const;

   /// \brief handles begin-contact callbacks and dispatches per-object-type logic.
   /// \param contact contact generated by box2d.
   void BeginContact(b2Contact* contact) override;

   /// \brief handles end-contact callbacks and decrements or clears related state.
   /// \param contact contact generated by box2d.
   void EndContact(b2Contact* contact) override;

   /// \brief runs pre-solve processing for contacts, including conveyor-belt behavior.
   /// \param contact contact being solved.
   /// \param oldManifold previous manifold provided by box2d.
   void PreSolve(b2Contact* contact, const b2Manifold* oldManifold) override;

   /// \brief processes contact impulses for player impact handling and projectile reactions.
   /// \param contact resolved contact.
   /// \param impulse impulse data for the resolved contact.
   void PostSolve(b2Contact* contact, const b2ContactImpulse* impulse) override;

   /// \brief prints current contact counters to stdout for debugging.
   void debug();

   /// \brief resets all tracked contact counters and one-way-wall state.
   void reset();

   /// \brief executes queued contact events with smash-over-damage priority conflict resolution.
   void processEvents();

   /// \brief returns the singleton contact listener used by the physics world.
   /// \return global game contact listener instance.
   static GameContactListener& getInstance();

private:
   /// \brief creates the singleton contact listener.
   GameContactListener() = default;

   /// \brief dispatches begin-contact handling for one fixture/user-data ordering.
   /// \param contact current contact pair.
   /// \param contact_fixture_a fixture treated as the active source.
   /// \param contact_fixture_b opposite fixture in the pair.
   /// \param fixture_node_a fixture node attached to contact_fixture_a.
   /// \param fixture_node_b fixture node attached to contact_fixture_b.
   /// \param fixture_user_data_b raw user data pointer of contact_fixture_b.
   void processBeginContact(
      b2Contact* contact,
      b2Fixture* contact_fixture_a,
      b2Fixture* contact_fixture_b,
      FixtureNode* fixture_node_a,
      FixtureNode* fixture_node_b,
      void* fixture_user_data_b
   );

   /// \brief dispatches end-contact handling for one fixture/user-data ordering.
   /// \param contact current contact pair.
   /// \param fixture_node_a fixture node treated as the active source.
   /// \param fixture_node_b opposite fixture node in the pair.
   /// \param contact_fixture_b opposite fixture in the pair.
   void processEndContact(b2Contact* contact, FixtureNode* fixture_node_a, FixtureNode* fixture_node_b, b2Fixture* contact_fixture_b);

   /// \brief processes post-solve effects for a fixture node and impulse value.
   /// \param node fixture node participating in the contact.
   /// \param impulse normal impulse reported by box2d.
   void processPostSolve(FixtureNode* node, float impulse);

   /// \brief activates a bouncer when contact begins.
   /// \param fixture_node fixture node expected to be a bouncer.
   void processBouncerContactBegin(FixtureNode* fixture_node);

   /// \brief forwards begin-contact events to a bubble cube.
   /// \param contact raw box2d contact.
   /// \param bubble fixture node expected to be a bubble cube.
   /// \param other other fixture node in contact.
   void processBubbleCubeContactBegin(b2Contact* contact, FixtureNode* bubble, FixtureNode* other);

   /// \brief forwards begin-contact events to a collapsing platform.
   /// \param contact raw box2d contact.
   /// \param fixture_node fixture node expected to be a collapsing platform.
   /// \param other other fixture node in contact.
   void processCollapsingPlatformContactBegin(b2Contact* contact, FixtureNode* fixture_node, FixtureNode* other);

   /// \brief counts deadly contact when a crusher touches the player.
   /// \param fixture_node fixture node on the opposing side of the crusher contact.
   void processCrusherContactBegin(FixtureNode* fixture_node);

   /// \brief counts deadly contact when a deadly fixture touches the player.
   /// \param fixture_node fixture node on the opposing side of the deadly contact.
   void processDeadlyContactBegin(FixtureNode* fixture_node);

   /// \brief handles enemy-to-player contact by queuing damage events or applying damage immediately.
   /// \param fixture_node_a fixture node representing the enemy side.
   /// \param fixture_node_b fixture node representing the opposing side.
   void processEnemyContactBegin(FixtureNode* fixture_node_a, FixtureNode* fixture_node_b);

   /// \brief tracks contact with death blocks and detects crushing against the player head sensor.
   /// \param fixture death-block fixture involved in the contact.
   /// \param fixture_user_data user data pointer from the opposing fixture.
   void processDeathBlockContactBegin(b2Fixture* fixture, void* fixture_user_data);

   /// \brief tracks contact with moving platforms and detects crushing against the player head sensor.
   /// \param fixture moving-platform fixture involved in the contact.
   /// \param fixture_user_data user data pointer from the opposing fixture.
   void processMovingPlatformContactBegin(b2Fixture* fixture, void* fixture_user_data);

   /// \brief forwards one-way-wall begin contact to the one-way-wall state handler.
   /// \param contact current contact.
   /// \param fixture fixture expected to belong to the player.
   void processOneWayWallContactBegin(b2Contact* contact, b2Fixture* fixture);

   /// \brief increments the generic player contact counter.
   void processPlayerContactBegin();

   /// \brief handles player foot-sensor begin contact, including smash-enemy detection.
   /// \param fixture_node opposing fixture node.
   /// \param fixture opposing fixture.
   void processPlayerFootSensorContactBegin(FixtureNode* fixture_node, b2Fixture* fixture);

   /// \brief updates head-sensor contact counters for begin-contact events.
   /// \param fixture opposing fixture.
   void processPlayerHeadSensorContactBegin(b2Fixture* fixture);

   /// \brief updates left-arm-sensor contact counters for begin-contact events.
   /// \param fixture opposing fixture.
   void processPlayerLeftArmSensorContactBegin(b2Fixture* fixture);

   /// \brief updates right-arm-sensor contact counters for begin-contact events.
   /// \param fixture opposing fixture.
   void processPlayerRightArmSensorContactBegin(b2Fixture* fixture);

   /// \brief handles projectile begin contact, including damage and projectile removal behavior.
   /// \param fixture_node_a fixture node representing the projectile.
   /// \param fixture_node_b opposing fixture node hit by the projectile.
   void processProjectileContactBegin(FixtureNode* fixture_node_a, FixtureNode* fixture_node_b);

   /// \brief forwards end-contact events to a bubble cube.
   /// \param bubble fixture node expected to be a bubble cube.
   /// \param other other fixture node leaving contact.
   void processBubbleCubeContactEnd(FixtureNode* bubble, FixtureNode* other);

   /// \brief forwards end-contact events to a collapsing platform.
   /// \param fixture_node_platform fixture node expected to be a collapsing platform.
   /// \param fixture_node_other other fixture node leaving contact.
   void processCollapsingPlatformContactEnd(FixtureNode* fixture_node_platform, FixtureNode* fixture_node_other);

   /// \brief decrements deadly contact count when a crusher stops touching the player.
   /// \param fixture_node opposing fixture node.
   void processCrusherContactEnd(FixtureNode* fixture_node);

   /// \brief decrements deadly contact count when deadly contact ends.
   /// \param fixture_node opposing fixture node.
   void processDeadlyContactEnd(FixtureNode* fixture_node);

   /// \brief clears death-block contact tracking when contact with the player ends.
   /// \param fixture_node opposing fixture node.
   void processDeathBlockContactEnd(FixtureNode* fixture_node);

   /// \brief clears moving-platform contact tracking when contact with the player ends.
   /// \param fixture_node opposing fixture node.
   void processMovingPlatformContactEnd(FixtureNode* fixture_node);

   /// \brief forwards one-way-wall end contact to restore default contact state.
   /// \param contact current contact.
   void processOneWayWallContactEnd(b2Contact* contact);

   /// \brief decrements the generic player contact counter.
   void processPlayerContactEnd();

   /// \brief updates foot-sensor counters for end-contact events.
   /// \param fixture_node opposing fixture node.
   /// \param fixture opposing fixture.
   void processPlayerFootSensorContactEnd(FixtureNode* fixture_node, b2Fixture* fixture);

   /// \brief updates left-arm-sensor counters for end-contact events.
   /// \param contact_fixture opposing fixture.
   void processPlayerLeftArmSensorContactEnd(b2Fixture* contact_fixture);

   /// \brief updates right-arm-sensor counters for end-contact events.
   /// \param contact_fixture opposing fixture.
   void processPlayerRightArmSensorContactEnd(b2Fixture* contact_fixture);

   /// \brief updates head-sensor counters for end-contact events.
   /// \param contact_fixture_b opposing fixture.
   void processPlayerHeadSensorContactEnd(b2Fixture* contact_fixture_b);

   /// \brief forwards significant player collision impulses to player impact handling.
   /// \param impulse normal impulse from post-solve.
   void processPostSolveImpulse(float impulse);

   /// \brief handles post-solve projectile impact behavior for sticky projectiles.
   /// \param node projectile fixture node.
   /// \param impulse normal impulse from post-solve.
   void processPostSolveProjectile(FixtureNode* node, float impulse);

   int32_t _count_foot_contacts = 0;
   int32_t _count_head_contacts = 0;
   int32_t _count_head_contacts_colliding = 0;
   int32_t _count_player_contacts = 0;
   int32_t _count_arm_left_contacts = 0;
   int32_t _count_arm_left_contacts_colliding = 0;
   int32_t _count_arm_right_contacts = 0;
   int32_t _count_arm_right_contacts_colliding = 0;
   int32_t _count_deadly_contacts = 0;
   int32_t _count_moving_platform_contacts = 0;
   int32_t _count_death_block_contacts = 0;
   bool _smashed = false;

   std::vector<std::shared_ptr<ContactEvent>> _events;
};
